project_id = "euhmubptofhzlsbxltas"

[functions.create-flutterwave-payment]
verify_jwt = true

[functions.flutterwave-webhook]
verify_jwt = false

[functions.generate-lesson-instances]
verify_jwt = true

[functions.generate-monthly-payments]
verify_jwt = true

[functions.generate-receipt]
verify_jwt = true

[functions.get-recipient-contacts]
verify_jwt = true

[functions.send-invoice]
verify_jwt = true

[functions.send-message]
verify_jwt = true

[functions.send-payment-reminders]
verify_jwt = true
